create table paciente (
   id integer generated by default as identity,
    email varchar(255),
    nome varchar(255),
    cpf varchar(255),
    telefone_id integer,
    endereco_id integer,
    primary key (id)
);

alter table paciente 
   add constraint FKmkmrjbm4d42x21wb7gxumauw5 
   foreign key (telefone_id) 
   references telefone;


alter table paciente 
   add constraint FKpus64vtl67yxnw2kimogd7abx 
   foreign key (endereco_id) 
   references endereco;
