create table medico (
   id integer generated by default as identity,
	email varchar(255),
	nome varchar(255),
	crm varchar(255),
	telefone_id integer,
	endereco_id integer,
	especialidade_id integer,
	primary key (id)
);

alter table medico 
   add constraint FKaibfvjvaoeip3uq95ei5pf5fg 
   foreign key (telefone_id) 
   references telefone;


alter table medico 
   add constraint FKdou0400stdgqmwjnsbwd09oy7 
   foreign key (endereco_id) 
   references endereco;


alter table medico 
   add constraint FKm4iro8s8g0v1rxsgrkb10ya27 
   foreign key (especialidade_id) 
   references especialidade;
