create table agenda (
     id integer generated by default as identity,
     data_consulta timestamp,
     disponivel boolean not null,
     medico_id integer,
     paciente_id integer,
     primary key (id)
);

alter table agenda 
   add constraint FKglfmdtrg0aejb5yapxu2u060a 
   foreign key (medico_id) 
   references medico;


alter table agenda 
   add constraint FKn7ykrshxh51wmik1pf0ruig54 
   foreign key (paciente_id) 
   references paciente;
